src/Entity/Artisan.php
<?php

namespace App\Entity;

use App\Repository\ArtisanRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtisanRepository::class)]
class Artisan
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    private ?string $image_profil = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getImageProfil(): ?string
    {
        return $this->image_profil;
    }

    public function setImageProfil(string $image_profil): self
    {
        $this->image_profil = $image_profil;

        return $this;
    }
}

src/Form/ArtisanType.php
<?php

namespace App\Form;

use App\Entity\Artisan;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtisanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('email')
            ->add('telephone')
            ->add('ville')
            ->add('image_profil')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artisan::class,
        ]);
    }
}

src/Controller/ArtisanController.php
<?php

namespace App\Controller;

use App\Entity\Artisan;
use App\Form\ArtisanType;
use App\Repository\ArtisanRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/artisan')]
class ArtisanController extends AbstractController
{
    #[Route('/', name: 'app_artisan_index', methods: ['GET'])]
    public function index(ArtisanRepository $artisanRepository): Response
    {
        return $this->render('artisan/index.html.twig', [
            'artisans' => $artisanRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_artisan_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArtisanRepository $artisanRepository): Response
    {
        $artisan = new Artisan();
        $form = $this->createForm(ArtisanType::class, $artisan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artisanRepository->save($artisan, true);

            return $this->redirectToRoute('app_artisan_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('artisan/new.html.twig', [
            'artisan' => $artisan,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artisan_show', methods: ['GET'])]
    public function show(Artisan $artisan): Response
    {
        return $this->render('artisan/show.html.twig', [
            'artisan' => $artisan,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_artisan_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Artisan $artisan, ArtisanRepository $artisanRepository): Response
    {
        $form = $this->createForm(ArtisanType::class, $artisan);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artisanRepository->save($artisan, true);

            return $this->redirectToRoute('app_artisan_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('artisan/edit.html.twig', [
            'artisan' => $artisan,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_artisan_delete', methods: ['POST'])]
    public function delete(Request $request, Artisan $artisan, ArtisanRepository $artisanRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artisan->getId(), $request->request->get('_token'))) {
            $artisanRepository->remove($artisan, true);
        }

        return $this->redirectToRoute('app_artisan_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/artisan/_delete_form.html.twig
<form method="post" action="{{ path('app_artisan_delete', {'id': artisan.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artisan.id) }}">
    <button class="btn">Delete</button>
</form>

templates/artisan/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/artisan/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artisan{% endblock %}

{% block body %}
    <h1>Edit Artisan</h1>

    {{ include('artisan/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_artisan_index') }}">back to list</a>

    {{ include('artisan/_delete_form.html.twig') }}
{% endblock %}

templates/artisan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artisan index{% endblock %}

{% block body %}
    <h1>Les Artisans</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Ville</th>
                <th>Image_profil</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artisan in artisans %}
            <tr>
                <td>{{ artisan.id }}</td>
                <td>{{ artisan.Nom }}</td>
                <td>{{ artisan.Prenom }}</td>
                <td>{{ artisan.email }}</td>
                <td>{{ artisan.telephone }}</td>
                <td>{{ artisan.ville }}</td>
                <td>{{ artisan.imageProfil }}</td>
                <td>
                    <a href="{{ path('app_artisan_show', {'id': artisan.id}) }}">show</a>
                    <a href="{{ path('app_artisan_edit', {'id': artisan.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_artisan_new') }}">Create new</a>
{% endblock %}

templates/artisan/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Artisan{% endblock %}

{% block body %}
    <h1>Create new Artisan</h1>

    {{ include('artisan/_form.html.twig') }}

    <a href="{{ path('app_artisan_index') }}">back to list</a>
{% endblock %}

templates/artisan/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artisan{% endblock %}

{% block body %}
    <h1>Artisan</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ artisan.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ artisan.Nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ artisan.Prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ artisan.email }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ artisan.telephone }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ artisan.ville }}</td>
            </tr>
            <tr>
                <th>Image_profil</th>
                <td>{{ artisan.imageProfil }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_artisan_index') }}">back to list</a>

    <a href="{{ path('app_artisan_edit', {'id': artisan.id}) }}">edit</a>

    {{ include('artisan/_delete_form.html.twig') }}
{% endblock %}